name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - uses: actions/checkout@v4
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@v2
      with:
        username: 'kkksenoww'
        reponame: 'pingwinchiki'
        token: ${{ secrets.GITHUB_TOKEN }}
